[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "contxt-sdk"
description = "Contxt SDK from ndustrial.io"
version = "1.0.0b7"
authors = ["ndustrial.io <dev@ndustrial.io>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/ndustrialio/contxt-sdk-python"
packages = [{include = "contxt"}]

[tool.poetry.dependencies]
python = ">=3.6.0"
argcomplete = "*"
auth0-python = "^3"
dataclasses = {version = "*", python = "<3.7"}
pyjwt = "*"
python-dateutil = "*"
python-jose-cryptodome = {version = "*", optional = true}
pytz = "*"
requests = "*"
tabulate = "*"
tqdm = "*"
tzlocal = "*"

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
flake8 = "*"
isort = "*"
mypy = "*"
pytest = "*"

[tool.poetry.extras]
server = ["python-jose-cryptodome"]

[tool.poetry.scripts]
contxt = "contxt.__main__:main"

[tool.black]
line-length = 88
target-version = ["py36", "py37"]
include = '(contxt|scripts|tests).*\.pyi?$'

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true