
[tool.black]
line-length = 88
target-version = ['py37']
include = '''
(
    assets_schema
  | novo
  | scripts
  | tests
  | scripts
)
.*\.pyi?$
'''
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | legacy
    | venv
    | vnv
    | \.wercker
    | \.mypy_cache
    | \.pytest_cache
    | \.egg-info
  )/
)
'''
