name: release

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@v1.0.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Publish to PyPI
        env:
          # https://github.com/python-poetry/poetry/issues/2359
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install poetry
          poetry publish --build --no-interaction
