name: release

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@v1.0.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
